service: apartment-manager

plugins:
  - serverless-s3-sync
  - serverless-cloudfront-invalidate

custom:

  # The domain name to be used
  domainName: ${param:domain}

  # CloudFront invalidation plugin configuration
  cloudfrontInvalidate:
    - distributionIdKey: 'CloudFrontDistributionId'
      items: # Add your files to invalidate here:
        - '/*'

  # S3 sync plugin configuration for static template pages built into site_build
  s3Sync:
    - bucketName: ${param:domain}
      localDir: site_build
      params:
        - '**/*.js':
            CacheControl: 'public, max-age=31536000'
        - '**/*.css':
            CacheControl: 'public, max-age=31536000'
        - '**/*.svg':
            CacheControl: 'public, max-age=86400'
        - '**/*.jpg':
            CacheControl: 'public, max-age=31536000'
        - '**/*.webp':
            CacheControl: 'public, max-age=31536000'
        - '**/*.png':
            CacheControl: 'public, max-age=31536000'
        - '**/*.gif':
            CacheControl: 'public, max-age=31536000'
        - '**/*.woff2':
            CacheControl: 'public, max-age=31536000'

provider:
  name: aws
  architecture: arm64
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 10
  region: us-west-2
  versionFunctions: false

  deploymentBucket:
    name: ${ssm:/serverless/deploymentbucket/prefix}-${self:provider.region}
    blockPublicAccess: true

  stackTags:
    Organization: ${param:domain}
    Project: 'Apartment Manager'

  environment:
    # Each DB table is reflected here in environment variables so it can be accessed in
    BUILDING_TABLE:
      Ref: BuildingTable
    AWS_NODEJS_CONNECTION_REUSE_ENABLED:
      1

functions:
  # Each data-serving page of the website will go here.
  # These are all the XHR which will fetch things from DynamoDB and return then as JSON for dropping into page templates
  buildings:
    description: >
      Return JSON structure of all the buildings and units
    handler: index.buildings
    events:
      - httpApi: GET /api/buildings
      - schedule:
          description: Scheduled ping to the lambda to keep it warm
          rate: rate(5 minutes)
          enabled: true
          input:
            keep-alive: true

resources:

  - ${file(resources/cloudfront-origin-access-identity.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/s3-policies.yml)}
  - ${file(resources/dns-records.yml)}
  - ${file(resources/certificate.yml)}
  - ${file(resources/cf-distribution.yml)}
  - ${file(resources/outputs.yml)}
  - ${file(resources/database.yml)}
