// CRITICAL: Import test setup FIRST before any other imports
import './test-setup';
import { dynamoDbMock, jest, resetAllMocks } from '../data/test-setup';

import { describe, it, expect, beforeEach, beforeAll } from 'bun:test';
import type { APIGatewayProxyEventV2 } from 'aws-lambda';
import { create, get, update, del } from '../../api/buildings';
import { mockGetResponse, mockPutResponse, mockUpdateResponse, mockDeleteResponse } from '../helpers/mock-responses';
import { getDefaultBuildingData } from '../../src/types';

const testBuildingInput = {
    // No buildingID - it's auto-generated by the API
    street: '123 Main St',
    city:   'Testville',
    state:  'TX',
    zip:    '75001'
    // buildingName will be auto-generated from street address
};

const testBuildingWithIds = {
    buildingID:   'eEUxh8XdGF1RsxfmwHPpYD', // Short-uuid format - used for responses
    buildingName: '123 Main', // Auto-generated from street
    street:       '123 Main St',
    city:         'Testville',
    state:        'TX',
    zip:          '75001'
};

describe('Buildings API - CRUD operations', () => {
    beforeAll(() => {
        resetAllMocks();
    });

    beforeEach(() => {
        jest.clearAllMocks();
        jest.restoreAllMocks();
        dynamoDbMock.mockReset();
    });

    describe('create endpoint', () => {
        it('should create a new building with auto-generated ID and name', async () => {
            // Expected building with defaults and auto-generated fields
            const expectedBuilding = {
                ...getDefaultBuildingData(),
                ...testBuildingWithIds,
                unitID: 'BUILDING'
            };

            dynamoDbMock.mockResolvedValueOnce(mockPutResponse(expectedBuilding));

            const event: Partial<APIGatewayProxyEventV2> = {
                body: JSON.stringify(testBuildingInput) // Input without buildingID
            };

            const result = await create(event as APIGatewayProxyEventV2);

            expect(result.statusCode).toBe(201);
            const responseBuilding = JSON.parse(result.body!);
            // Check that buildingID was auto-generated (should be short-uuid format)
            expect(responseBuilding.buildingID).toMatch(/^[\w-]{22}$/);
            // Check that buildingName was auto-generated from street address
            expect(responseBuilding.buildingName).toBe('123 Main');
            // Check that input fields are preserved
            expect(responseBuilding.street).toBe(testBuildingInput.street);
            expect(responseBuilding.city).toBe(testBuildingInput.city);
            expect(responseBuilding.state).toBe(testBuildingInput.state);
            expect(responseBuilding.zip).toBe(testBuildingInput.zip);
            // Check that defaults are applied
            expect(responseBuilding.acceptsOnlineApplications).toBe(true);
            expect(responseBuilding.leaseLength).toBe(12);
            expect(responseBuilding.photos).toEqual([]);
            expect(dynamoDbMock).toHaveBeenCalledTimes(1);
        });

        it('should reject invalid buildingID format', async () => {
            // Input that includes invalid buildingID (should be rejected)
            const inputWithId = { ...testBuildingInput, buildingID: 'should-be-ignored' };

            const event: Partial<APIGatewayProxyEventV2> = {
                body: JSON.stringify(inputWithId)
            };

            const result = await create(event as APIGatewayProxyEventV2);

            expect(result.statusCode).toBe(400);
            const error = JSON.parse(result.body!);
            expect(error.error).toBe('Validation failed');
            expect(error.errors.buildingID).toContain('must be a valid building ID format');
        });

        it('should surface DynamoDB errors', () => {
            dynamoDbMock.mockRejectedValueOnce(new Error('Database failure'));

            const event: Partial<APIGatewayProxyEventV2> = {
                body: JSON.stringify(testBuildingInput)
            };

            expect(create(event as APIGatewayProxyEventV2)).rejects.toThrow('Database failure');
        });
    });

    describe('get endpoint', () => {
        it('should retrieve a building', async () => {
            dynamoDbMock.mockResolvedValueOnce(mockGetResponse({ ...testBuildingWithIds, unitID: 'BUILDING' }));

            const event: Partial<APIGatewayProxyEventV2> = {
                pathParameters: { buildingID: testBuildingWithIds.buildingID }
            };

            const result = await get(event as APIGatewayProxyEventV2);

            expect(result.statusCode).toBe(200);
            const data = JSON.parse(result.body!);
            expect(data.buildingID).toBe(testBuildingWithIds.buildingID);
            expect(data.buildingName).toBe('123 Main'); // Building name included
            expect(dynamoDbMock).toHaveBeenCalledTimes(1);
        });

        it('should return 404 for invalid buildingID format', async () => {
            const event: Partial<APIGatewayProxyEventV2> = {
                pathParameters: { buildingID: 'bad id!' } // Invalid format
            };

            const result = await get(event as APIGatewayProxyEventV2);

            expect(result.statusCode).toBe(404);
            expect(result.body).toBe('Not Found');
        });

        it('should surface DynamoDB errors', () => {
            dynamoDbMock.mockRejectedValueOnce(new Error('DB error'));

            const event: Partial<APIGatewayProxyEventV2> = {
                pathParameters: { buildingID: testBuildingWithIds.buildingID }
            };

            expect(get(event as APIGatewayProxyEventV2)).rejects.toThrow('DB error');
        });
    });

    describe('update endpoint', () => {
        it('should update a building', async () => {
            // Updates need buildingID and buildingName to pass validation
            const updates = {
                buildingID:   testBuildingWithIds.buildingID, // Required by validation
                buildingName: '123 Main', // Provide building name to pass validation
                city:         'New City'
            };
            const expectedResponse = { ...testBuildingWithIds, ...updates, buildingName: '123 Main', unitID: 'BUILDING' };
            dynamoDbMock.mockResolvedValueOnce(mockUpdateResponse(expectedResponse));

            const event: Partial<APIGatewayProxyEventV2> = {
                pathParameters: { buildingID: testBuildingWithIds.buildingID },
                body:           JSON.stringify(updates)
            };

            const result = await update(event as APIGatewayProxyEventV2);

            expect(result.statusCode).toBe(200);
            const data = JSON.parse(result.body!);
            expect(data.city).toBe('New City');
            expect(data.buildingID).toBe(testBuildingWithIds.buildingID); // Preserved
            expect(data.buildingName).toBe('123 Main'); // Preserved or regenerated
            expect(dynamoDbMock).toHaveBeenCalledTimes(1);
        });

        it('should return 404 for invalid buildingID format', async () => {
            const event: Partial<APIGatewayProxyEventV2> = {
                pathParameters: { buildingID: 'bad id!' }, // Invalid short-uuid format
                body:           JSON.stringify({ city: 'New City' })
            };

            const result = await update(event as APIGatewayProxyEventV2);

            expect(result.statusCode).toBe(404);
            expect(result.body).toBe('Not Found');
        });

        it('should handle DynamoDB failures', async () => {
            dynamoDbMock.mockRejectedValueOnce(new Error('Database error'));
            dynamoDbMock.mockRejectedValueOnce(new Error('Database error'));

            const event: Partial<APIGatewayProxyEventV2> = {
                pathParameters: { buildingID: testBuildingWithIds.buildingID },
                body:           JSON.stringify({
                    buildingID:   testBuildingWithIds.buildingID, // Required by validation
                    buildingName: '123 Main', // Provide building name to pass validation
                    city:         'New City'
                })
            };

            const result = await update(event as APIGatewayProxyEventV2);

            expect(result.statusCode).toBe(500);
            const body = JSON.parse(result.body!);
            expect(body.error).toBe('Internal server error during update');
        });
    });

    describe('delete endpoint', () => {
        it('should delete a building', async () => {
            dynamoDbMock.mockResolvedValueOnce(mockDeleteResponse());

            const event: Partial<APIGatewayProxyEventV2> = {
                pathParameters: { buildingID: testBuildingWithIds.buildingID }
            };

            const result = await del(event as APIGatewayProxyEventV2);

            expect(result.statusCode).toBe(204);
            expect(result.body).toBe('');
            expect(dynamoDbMock).toHaveBeenCalledTimes(1);
        });

        it('should return 404 for invalid buildingID format', async () => {
            const event: Partial<APIGatewayProxyEventV2> = {
                pathParameters: { buildingID: 'bad id!' } // Invalid short-uuid format
            };

            const result = await del(event as APIGatewayProxyEventV2);

            expect(result.statusCode).toBe(404);
            expect(result.body).toBe('Not Found');
        });

        it('should handle DynamoDB failures', async () => {
            dynamoDbMock.mockRejectedValueOnce(new Error('Delete failed'));

            const event: Partial<APIGatewayProxyEventV2> = {
                pathParameters: { buildingID: testBuildingWithIds.buildingID }
            };

            const result = await del(event as APIGatewayProxyEventV2);

            expect(result.statusCode).toBe(404);
            expect(result.body).toBe('Not Found');
        });
    });
});
